include: package:pedantic/analysis_options.yaml

linter:
  rules:
    prefer_single_quotes: false
    library_prefixes: false

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
